### ISSUE TITLE
Support for alternative routers (for example TanStack Router)

### ISSUE THREAD

**Issue by ChristopherHaws** [taro-28/tanstack-table-search-params#13]
Hey! This library is exactly what I am looking for, but we don't use NextJS, we use Tanstack Router with client-side routing. Any chance the router types can be abstracted to allow for different state storage implementations? Some other implementations which could be useful are local or session storage.

Here is a link to their sample project which shows how this can be done with Tanstack Router:
- https://tanstack.com/table/latest/docs/framework/react/examples/query-router-search-params
- path: `src/hooks/useFilters.ts`

I would be happy to contribute the change, but I would need to know which direction you would want to take with the implementation - primarily if you would want the nextjs and tanstack router implementations to be packaged in separate packages or just as submodules of the core package with optional peer dependencies.

Thanks!

**Comment by taro-28** [comment]
@ChristopherHaws 

Hello! Thank you for finding this unfinished project! (I apologize for the delayed response as well.)

I will try to see if I can make it compatible with TanStack Router, so please wait a little longer!

**Comment by taro-28** [comment]
I've confirmed that the following implementation still works with Tanstack Router, but what do you think?

https://github.com/taro-28/tanstack-table-search-params/blob/a9c3ddf68ea52f8aea4120d13a30726f0df89f54/examples/tanstack-router/src/routes/index.tsx#L16-L42

However, honestly, passing `search` to `navigate` isn't as straightforward as I'd like, so I'm planning to come up with another solution eventually. 🙏
